name: 
permissions:
  packages: write

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - uses: ko-build/setup-ko@v0.6

      - run: ko build --platform=linux/amd64,linux/arm64 --bare